# thu7NdwWnKWT1eYb
# dwitithaker04_db_user

LOW_PROGRESS_THRESHOLD = 0.5
WEAK_THRESHOLD = 2

SPLIT_WEAK = 0.5
SPLIT_NEW = 0.3
SPLIT_REVISION = 0.2

MIN_TASK_MINUTES = 30
LOW_HOURS_ONE_TASK_MAX_MINUTES = 60
REVISION_AGE_DAYS = 3
NEW_TOPIC_PLACEHOLDER = "Next topic"